import { BadgeIndianRupee, Car, Clock, HeartHandshake, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import AnimatedSection from "../components/AnimatedSection";
import StatsCounter from "../components/StatsCounter";
import PageHero from "../components/PageHero";

const reasons = [[ShieldCheck, "Verified, Professional Drivers", "Experienced with local and outstation routes."], [Car, "Well-Maintained Fleet", "Regular safety checks before every trip."], [Clock, "24/7 Availability", "Support whenever plans change."], [BadgeIndianRupee, "Transparent Pricing", "No hidden charges, ever."]];
const services = [[Car, "Local & City Travel"], [Sparkles, "Outstation Trips"], [Clock, "Airport Transfers"], [UsersRound, "Corporate & Events"], [HeartHandshake, "Family & Group Tours"]];

function AboutPage() {
  return <>
    <PageHero eyebrow="About Sangaurii Tours and Travels" title="About Us" description="Your Trusted Travel Partner for Over a Decade. For 10 years, we have delivered seamless journeys for family vacations, corporate trips, outstation getaways, and urgent airport transfers." image="/assets/gallery/group-outings/group-outing-01.jpeg" />
    <AnimatedSection className="bg-off-white py-12" stagger><div className="site-container grid gap-8 sm:grid-cols-2 lg:grid-cols-4"><StatsCounter Icon={Clock} value={10} label="Years of service" /><StatsCounter Icon={UsersRound} value={5000} label="Happy travellers" /><StatsCounter Icon={Car} value={30} suffix="+" label="Fleet choices" /><StatsCounter Icon={ShieldCheck} value={100} suffix="%" label="Trusted reputation" /></div></AnimatedSection>
    <AnimatedSection className="section-pad" stagger><div className="site-container"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-golden-orange">Why travel with us</p><h2 className="section-heading-accent mt-3 font-display text-4xl font-bold text-deep-navy">A decade of excellence, with every journey</h2><p className="mt-6 leading-8 text-dark-text/72">Sangaurii has grown from a local transport provider into one of the region’s most trusted travel and car rental partners—built on punctuality, comfort and clear communication.</p></div><div className="mt-12 grid gap-px overflow-hidden border border-forest-green/15 bg-forest-green/15 sm:grid-cols-2 lg:grid-cols-4">{reasons.map(([Icon, title, text]) => <article key={title} data-reveal-item className="bg-off-white p-7"><Icon className="text-golden-orange" size={31} /><h3 className="mt-5 font-display text-xl font-bold text-deep-navy">{title}</h3><p className="mt-3 text-sm leading-6 text-dark-text/70">{text}</p></article>)}</div></div></AnimatedSection>
    <section className="bg-[#102d24] py-12"><div className="site-container grid gap-5 md:grid-cols-3"><img src="/assets/gallery/temple-tours/temple-tour-02.jpeg" alt="Temple tour group" className="h-56 w-full object-cover" /><img src="/assets/gallery/railway-departure/departure-01.jpeg" alt="Railway departure" className="h-56 w-full object-cover" /><img src="/assets/gallery/boating/boating-01.jpeg" alt="Boating trip" className="h-56 w-full object-cover" /></div></section>
    <AnimatedSection className="section-pad bg-white" stagger><div className="site-container"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-golden-orange">Our core services</p><h2 className="section-heading-accent mx-auto mt-3 font-display text-4xl font-bold text-deep-navy">Travel made simple, every time</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{services.map(([Icon, label]) => <div key={label} data-reveal-item className="border border-forest-green/20 p-6 text-center transition hover:-translate-y-1 hover:border-golden-orange"><Icon className="mx-auto text-forest-green" size={29} /><p className="mt-4 font-bold text-deep-navy">{label}</p></div>)}</div></div></AnimatedSection>
    <section className="bg-[#e9dfc8] py-24 text-center"><div className="site-container max-w-4xl"><span className="font-display text-7xl leading-none text-golden-orange">“</span><p className="font-display text-3xl italic leading-relaxed text-deep-navy sm:text-4xl">Your journey, our commitment. Thank you for trusting Sangaurii for the past 10 years—we look forward to driving you forward.</p><p className="mt-7 text-xs font-bold uppercase tracking-[.18em] text-forest-green">Our vision: safer journeys, smarter booking, and comfort at the center of everything we do.</p></div></section>
  </>;
}

export default AboutPage;
